// icons.ts

import {
  Calendar1Icon,
  CalendarIcon,
  CalendarRangeIcon,
  CheckSquareIcon,
  ClockIcon,
  EyeOffIcon,
  FileInputIcon,
  HashIcon,
  ImageIcon,
  LinkIcon,
  ListChecksIcon,
  LockIcon,
  MailIcon,
  PaletteIcon,
  PhoneIcon,
  RadioIcon,
  RotateCcwIcon,
  SearchIcon,
  SendIcon,
  SlidersIcon,
  SquareIcon,
  SquareMousePointerIcon,
  TextCursorIcon,
} from "lucide-react";

export const inputTypeIconMap = {
  button: SquareIcon,
  checkbox: CheckSquareIcon,
  color: PaletteIcon,
  date: CalendarIcon,
  "datetime-local": CalendarIcon,
  email: MailIcon,
  file: FileInputIcon,
  hidden: EyeOffIcon,
  image: ImageIcon,
  month: CalendarRangeIcon,
  number: HashIcon,
  password: LockIcon,
  radio: RadioIcon,
  range: SlidersIcon,
  reset: RotateCcwIcon,
  search: SearchIcon,
  submit: SendIcon,
  tel: PhoneIcon,
  text: TextCursorIcon,
  time: ClockIcon,
  url: LinkIcon,
  week: Calendar1Icon,
  "select-one": SquareMousePointerIcon,
  "select-multiple": ListChecksIcon,
} as const;
