import { ScrapedForm } from "~/lib/models/FormField";

export const MOCK_SCRAPED_FORM: ScrapedForm = {
  fields: [
    {
      id: "field_1",
      name: "username",
      label: "What should we call you?",
      type: "text",
      selector: 'data-digi-field="username"]',
    },
    { id: "field_2", name: "xp", label: "Rate your experience", type: "range", selector: '[data-digi-field="xp"]' },
    {
      id: "field_3",
      name: "email",
      label: "Only accepting Gmail accounts",
      type: "email",
      selector: '[data-digi-field="email"]',
    },
    { id: "field_4", name: "password", label: "Password", type: "password", selector: '[data-digi-field="password"]' },
    {
      id: "field_5",
      name: "DoB",
      label: "Date of birth",
      type: "date",
      selector: '[data-digi-field="birthdate"]',
    },
    {
      id: "field_6",
      name: "appointment",
      label: "Appointment (date/time)",
      type: "datetime-local",
      selector: '[data-digi-field="appointment"]',
    },
    {
      id: "field_7",
      name: "colorChallenge",
      label: "Prove you don't see color",
      type: "color",
      selector: '[data-digi-field="favColor"]',
    },
    {
      id: "field_8",
      name: "profilePic",
      label: "Upload profile pic",
      type: "file",
      selector: '[data-digi-field="profilePic"]',
    },
    {
      id: "field_9",
      name: "subscribe",
      label: "Subscribe to newsletter?",
      type: "checkbox",
      selector: '[data-digi-field="subscribe"]',
    },
    { id: "field_10", name: "gender", label: "Gender", type: "radio", selector: '[data-digi-field="gender"]' },
    { id: "field_11", name: "contact", label: "Contact number", type: "tel", selector: '[data-digi-field="contact"]' },
    { id: "field_12", name: "website", label: "Your website", type: "url", selector: '[data-digi-field="website"]' },
    {
      id: "field_13",
      name: "apptTime",
      label: "Preferred time",
      type: "time",
      selector: '[data-digi-field="apptTime"]',
    },
    {
      id: "field_14",
      name: "birthMonth",
      label: "Birth month",
      type: "month",
      selector: '[data-digi-field="birthMonth"]',
    },
    {
      id: "field_15",
      name: "birthWeek",
      label: "Birth week of year",
      type: "week",
      selector: '[data-digi-field="birthWeek"]',
    },
    {
      id: "field_16",
      name: "country",
      label: "Select your country",
      type: "select-one",
      selector: '[data-digi-field="country"]',
    },
    {
      id: "field_17",
      name: "hobbies",
      label: "Choose your hobbies",
      type: "select-multiple",
      selector: '[data-digi-field="hobbies"]',
    },
  ],
};
